format = """
[](#7FC281)\
$username\
[](bg:#EDB3D8 fg:#7FC281)\
$directory\
[](fg:#EDB3D8)\
$fill\
[](#D3946F)\
$git_branch$git_status$git_metrics\
[](fg:#6491CC bg:#D3946F)\
$time\
[ ](fg:#6491CC)\
$line_break$character
"""
palette = "catppuccin_mocha"
add_newline = true

[fill]
symbol = " "

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[username]
show_always = true
style_user = "bg:#7FC281 fg:#51514F"
style_root = "bg:#7FC281 fg:#51514F"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#EDB3D8 fg:#51514F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = "⾕"

[git_branch]
symbol = ""
style = "bg:#D3946F fg:#51514F"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#D3946F fg:#51514F"
format = '([\[$all_status$ahead_behind\] ]($style))'
#format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
disabled = false
added_style = "bg:#D3946F fg:#51514F"
format = '[+$added/-$deleted ]($added_style)'

[time]
disabled = false
time_format = " %R" # Hour:Minute Format
style = "bg:#6491CC fg:#51514F"
format = '[$time ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
